version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: motorrent_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: motorrent
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: motorrent_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: motorrent_rabbit
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  pgdata:
  mongodata:
